Do not pass `null` to the `$text` parameter of adapter's `notify()`
The `$text` parameter is documented to take a `string`, not a `?string` and in
fact the Console adapter unconditionally calls a variant of `substr()` on the
given `$text` to shorten it to the configured display width.

With PHP 8.1 this fails, because native functions no longer accept `null` for a
string parameter:

> TypeError: grapheme_substr(): Argument #1 ($string) must be of type string, null given in […]

Signed-off-by: Tim Düsterhus <duesterhus@woltlab.com>
(cherry picked from commit 965a4479b5f8b7df054c0a4a52749d272f752939)